create or replace 
PROCEDURE BPM_DOC_DOWNLOAD_MOVE_HISTORY
( 
IN_WI_NAME NVARCHAR2,
IN_CID NVARCHAR2,
IN_STATUS NVARCHAR2
)
AS
V_QUERY 			NVARCHAR2(1000);
BEGIN
    V_QUERY := 'UPDATE BPM_DOC_DOWNLOAD SET STATUS = :STATUS WHERE WORKITEM_NUMBER = :WI_NAME AND CID = :CID ';
       dbms_output.put_line('2');
    dbms_output.put_line(V_QUERY);
    EXECUTE IMMEDIATE  TO_CHAR(V_QUERY) USING IN_STATUS, IN_WI_NAME;
    COMMIT;
    SAVEPOINT MOVE_TO_HISTORY;
    V_QUERY := 'INSERT INTO BPM_DOC_DOWNLOAD_HISTORY (WORKITEM_NUMBER,THREAD_NAME,STATUS,CREATEDDATETIME,CID) SELECT 
	            WORKITEM_NUMBER,THREAD_NAME,STATUS,CREATEDDATETIME,CID
            FROM BPM_DOC_DOWNLOAD WHERE WORKITEM_NUMBER = :WI_NAME AND CID = :CID ';
     dbms_output.put_line('3');
    dbms_output.put_line(V_QUERY);
    EXECUTE IMMEDIATE TO_CHAR(V_QUERY) USING IN_WI_NAME;
    V_QUERY := 'DELETE FROM BPM_DOC_DOWNLOAD WHERE WORKITEM_NUMBER = :WI_NAME AND CID = :CID ';
    dbms_output.put_line('4');
    dbms_output.put_line(V_QUERY);
    EXECUTE IMMEDIATE TO_CHAR(V_QUERY) USING IN_WI_NAME;
    COMMIT;
    EXCEPTION 
      WHEN OTHERS THEN
      ROLLBACK TO MOVE_TO_HISTORY;
  END;