# Global configuration
status = warn
name = NewgenConfig

# INFO Rolling File Appender
appender.info.type = RollingFile
appender.info.name = In
appender.info.fileName = Logs/Info.log
appender.info.filePattern = Logs/Info-%i.log
appender.info.layout.type = PatternLayout
appender.info.layout.pattern = %d{dd MMM yyyy HH:mm:ss} %-5p (%t) %c [%r]: %m%n
appender.info.policies.type = Policies
appender.info.policies.size.type = SizeBasedTriggeringPolicy
appender.info.policies.size.size = 100MB
appender.info.strategy.type = DefaultRolloverStrategy
appender.info.strategy.max = 50

# ERROR Rolling File Appender
appender.error.type = RollingFile
appender.error.name = E
appender.error.fileName = Logs/Error.log
appender.error.filePattern = Logs/Error-%i.log
appender.error.layout.type = PatternLayout
appender.error.layout.pattern = %d{dd MMM yyyy HH:mm:ss} %-5p (%t) %c [%r]: %m%n
appender.error.policies.type = Policies
appender.error.policies.size.type = SizeBasedTriggeringPolicy
appender.error.policies.size.size = 100MB
appender.error.strategy.type = DefaultRolloverStrategy
appender.error.strategy.max = 50

# LOGGERS
# Info Logger
logger.info.name = Info
logger.info.level = info
logger.info.additivity = false
logger.info.appenderRef.in.ref = In

# Error Logger
logger.error.name = Error
logger.error.level = error
logger.error.additivity = false
logger.error.appenderRef.e.ref = E

# Root Logger (Standard out)
rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT