log =/appl/Newgen/BPM/Services/MSRDocDownload/Logs


##WBG RETRY LOGS
log4j.rootLogger=DEBUG,MSRDoc
log4j.appender.MSRDoc=org.apache.log4j.RollingFileAppender
log4j.appender.MSRDoc.File=${log}/info.log
log4j.appender.MSRDoc.MaxFileSize=5MB
log4j.appender.MSRDoc.MaxBackupIndex=10
log4j.appender.MSRDoc.layout=org.apache.log4j.PatternLayout
log4j.appender.MSRDoc.layout.conversionPattern=%d{dd MMM yyyy HH:mm:ss} %-5p (%t) %c [%r]:%m%n