spring.application.name=Ecommerce

spring.profiles.active=dev

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# File
project.image=images/

#SWAGGER CONFIG
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.apex.ecommerce.project=DEBUG



