spring.application.name=Ecommerce

# Database configuration
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:apexDB
spring.datasource.username=apex
spring.datasource.password=uchiha

# Hibernate configuration
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# File
project.image=image/

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookieName=ApexCookie

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.apex.ecommerce.project=DEBUG