# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JWT
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=5000000
spring.app.jwtCookieName=ApexCookie

# URLs
frontend.url=${FRONTEND_URL}
image.base.url=${IMAGE_BASE_URL}

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}

# Disable Swagger in prod
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# Stricter JPA in prod
#spring.jpa.hibernate.ddl-auto=validate