#if DUMMYCALL = true, dummyResponse will be sent
DUMMYCALL=false
ConnectionTimeOut=120000
ReadTimeOut=120000

EndPointURL=https://bhhqmwt1:8443/MiddlewareWebService/services/MiddlewareHandler?wsdl
#IScoreURL=https://aubegtstmidware:8443/MiddlewareWebService/services/MiddlewareHandler?wsdl 
IScoreURL=https://bhhqmwt1:8443/MiddlewareWebService/services/MiddlewareHandler?wsdl
METHODNAME=POST
SESSIONTOKEN=UkxPU0AhMTI=