# Root logger option  . Possible Options : TRACE,DEBUG,INFO,WARN,ERROR,FATAL,ALL
log4j.rootLogger=ALL

log4j.category.ServiceRequestsLogger=ALL, ServiceRequestsLogger
log4j.additivity.ServiceRequestsLogger=false

log4j.category.SRLogger=ALL, SRLogger
log4j.additivity.SRLogger=false

log4j.appender.ServiceRequestsLogger=org.apache.log4j.RollingFileAppender  
log4j.appender.ServiceRequestsLogger.File=CustomLog/ServiceRequests_Logs/ServiceRequests_Log.xml
log4j.appender.ServiceRequestsLogger.MaxFileSize=2000KB
log4j.appender.ServiceRequestsLogger.MaxBackupIndex=10
log4j.appender.ServiceRequestsLogger.layout=org.apache.log4j.PatternLayout
log4j.appender.ServiceRequestsLogger.layout.ConversionPattern=[%5p] %d{dd-MMM-yyyy HH:mm:ss} (%F:%L)%n%m%n%n

log4j.appender.SRLogger=org.apache.log4j.RollingFileAppender  
log4j.appender.SRLogger.File=CustomLog/SR_Logs/SR_Log.xml
log4j.appender.SRLogger.MaxFileSize=2000KB
log4j.appender.SRLogger.MaxBackupIndex=10
log4j.appender.SRLogger.layout=org.apache.log4j.PatternLayout
log4j.appender.SRLogger.layout.ConversionPattern=[%5p] %d{dd-MMM-yyyy HH:mm:ss} (%F:%L)%n%m%n%n
