#######################################################################
#																	  #				
#  Omniflow Server - Log4j Configuration							  #
#  Class Names and Logger Names are Case-Sensitive					  #
#  In Case of File Appenders, specify FileNames only				  #				
#																	  #				
#######################################################################

# Root logger option  
log4j.rootLogger=ALL

#Error.log
log4j.logger.RPerrorLogger=debug, E
#log4j.additivity.RPerrorLogger=false
log4j.appender.E=org.apache.log4j.RollingFileAppender
log4j.appender.E.File=Error.log
log4j.appender.E.MaxBackupIndex=10
log4j.appender.E.MaxFileSize=2MB
log4j.appender.E.layout=org.apache.log4j.PatternLayout
log4j.appender.E.layout.ConversionPattern=[%5p] %d{dd-MMM-yyyy HH:mm:ss} (%F:%L)%n%m%n%n

#Console.log
log4j.logger.RPconsoleLogger=debug, C
log4j.additivity.RPconsoleLogger=false
log4j.appender.C=org.apache.log4j.RollingFileAppender
log4j.appender.C.File=Console.log
log4j.appender.C.MaxBackupIndex=10
log4j.appender.C.MaxFileSize=2MB
log4j.appender.C.layout=org.apache.log4j.PatternLayout
log4j.appender.C.layout.ConversionPattern=[%5p] %d{dd-MMM-yyyy HH:mm:ss} (%F:%L)%n%m%n%n

#Transaction.log
log4j.logger.RPtransactionLogger=debug, T
log4j.additivity.RPtransactionLogger=false
log4j.appender.T=org.apache.log4j.RollingFileAppender
log4j.appender.T.File=Transaction.log
log4j.appender.T.MaxBackupIndex=10
log4j.appender.T.MaxFileSize=2MB
log4j.appender.T.layout=org.apache.log4j.PatternLayout
log4j.appender.T.layout.ConversionPattern=[%5p] %d{dd-MMM-yyyy HH:mm:ss} (%F:%L)%n%m%n%n

#XML.log
log4j.logger.RPXMLLogger=debug, X
log4j.additivity.RPXMLLogger=false
log4j.appender.X=org.apache.log4j.RollingFileAppender
log4j.appender.X.File=XML.log
log4j.appender.X.MaxBackupIndex=10
log4j.appender.X.MaxFileSize=2MB
log4j.appender.X.layout=org.apache.log4j.PatternLayout
log4j.appender.X.layout.ConversionPattern=[%5p] %d{dd-MMM-yyyy HH:mm:ss} (%F:%L)%n%m%n%n